### ISSUE TITLE
Give information on vim highlight group under the cursor

### ISSUE THREAD

**Issue by reportaman** [nvim-treesitter/playground#67] opened 2022-02-13 16:21 UTC
When treesitter is enabled for a language, the ``:TSHighlightCapturesUnderCursor`` command does not return complete information for people who would want to look what vim highlight group is currently applied there.

For Lua's treesitter disabled, it shows the highlight groups; not sure why there are 3 of them. It looks confusing... Should I always look at the last line to find the actual highlight group under the cursor? ``PreProc`` is the correct answer here. If I modify the color of insert_before would change accordingly.
<img width="310" alt="Screen Shot 2022-02-13 at 7 58 44 AM" src="https://user-images.githubusercontent.com/71736629/153762112-7a662e0c-f4aa-48e1-8a8d-20020d0cd129.png">

For Lua's treesitter enabled, it does not show the mapping to Vim highlight group... so there is no way to know what highlight group to modify.
<img width="347" alt="Screen Shot 2022-02-13 at 7 59 34 AM" src="https://user-images.githubusercontent.com/71736629/153762104-8db99715-d04b-49bd-ae16-dace68d6111f.png">

NOTE: The reason I ask for Vim highlight group is I maintain a small bunch of color schemes that I use in both vim and neovim. And its duplication of work to specify treesitter-specific highlight groups in them. Given the name ``TSFunction`` makes me wonder if all treesitter highlight groups are the same as their vim counterparts without the prefix ``TS``. If that is so, then I guess we are ok.

**Comment by theHamsta** [comment] 2022-02-13 18:44
This is because tree-sitter disables syntax. Use `:set syntax=on` or `      additional_vim_regex_highlighting = true` in your nvim-treesitter setup call for the highlight module

**Comment by reportaman** [comment] 2022-02-13 19:29
@theHamsta Thats not the point. The thing is if I do hi Function ctermfg=1, it does change the color TSFunction here. Would it be possible to follow the path and add TSFunction (<equivalent_vim_highlight_group>)

**Comment by clason** [comment] 2022-03-28 20:27
duplicate of #70 (in the sense that that issue is a superset of this one)

**Closed by clason** 2022-03-28 20:27 UTC
