### ISSUE TITLE
Nodes not highlited when navigating in source file

### ISSUE THREAD

**Issue by fisher-j** [nvim-treesitter/playground#100] opened 2022-11-04 16:02 UTC
I'm using neovim 0.9.0 and recently updated plugins. When I navigate in the source file, the corresponding node is not highlighted or focused in the playground window. Is there a setting for this or is it unexpected behavior?

![WindowsTerminal_Gq9wwpWpVK](https://user-images.githubusercontent.com/63136705/200021245-304414e2-bc8f-41bb-832f-886ac6526b80.gif)

**Comment by clason** [comment] 2022-11-04 17:33
Duplicate of #69

(It would be nice, someone just has to implement it.)

**Closed by clason** 2022-11-04 17:34 UTC
