### ISSUE TITLE
Node under cursor not highlighted as before

### ISSUE THREAD

**Issue by osa1** [nvim-treesitter/playground#24] opened 2021-02-14 06:28 UTC
A while ago if I open the query buffer and move the cursor around in the code buffer, the node for the code under the cursor would be highlighted/selected in the query buffer. This behavior is also shown in the screenshot in the README of this project. 

This was very useful, but it seems like it got broken at some point. Currently it's very difficult to find a node for a code because the query buffer no longer follows the cursor in the code buffer.

**Comment by steelsojka** [comment] 2021-02-14 13:24
What version nvim are you using? I can't reproduce it.

**Comment by osa1** [comment] 2021-02-14 13:25
- NVIM v0.5.0-dev+2894-g5ad32885d
- playground 7e373e5

**Comment by steelsojka** [comment] 2021-02-14 13:29
I can't check which version is edge but I would suggest using the latest
version of both. The playground was reworked to support nested languages
that was merged into neovim. I can't check is those versions are the latest
(mobile).

**Comment by osa1** [comment] 2021-02-14 13:30
Those versions are latest, yes. I updated both today, from git repos, master branches.

**Comment by steelsojka** [comment] 2021-02-14 13:40
Can you provide a reproducible file/scenario I can use to reproduce?

**Closed** 2021-02-17 20:58 UTC

**Comment by osa1** [comment] 2021-02-18 03:33
Unfortunately this is still not fixed. I will upload a gif if I can figure out how to record gifs on Linux.

**Comment by steelsojka** [comment] 2021-02-18 12:01
Hmmm. I'm thinking this may be something localized to your install. The fix
provided fixed the highlighting when not displaying anonymous nodes which
was the issue I was seeing. Can you provide a minimal reproduction with a
minimal init.vim/lua?

**Comment by stumash** [comment] 2021-07-22 17:22
I'm on newest nvim and playground and also get nothing when the cursor is sitting on the capture name
e.g.
```
[
    "for"
    "while"
    "if"
    "else"
] @keyword
```

**Comment by stsewd** [comment] 2021-07-30 04:13
@stumash can you share all the steps you are following and the files you are using?

**Comment by stumash** [comment] 2021-08-03 22:17
I guess if this gets resolved it will be here https://github.com/nvim-treesitter/playground/issues/51
